platform :ios, '16.4'

target 'HelloWorld' do
  use_frameworks!
  pod 'netfox'
  pod 'SwiftDate'
  pod 'SwiftGen'
  pod 'MMKV'
  pod 'Alamofire'
  pod 'TrustKit'
end
post_install do |installer|
  installer.generated_projects.each do |project|
      project.targets.each do |target|
          target.build_configurations.each do |config|
              config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '16.4'
          end
      end
  end
  system("bundle install")
end