# Uncomment the next line to define a global platform for your project
platform :ios, '14.1'

target 'Infrastructure' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'MMKV'
  pod 'Alamofire'
  pod 'TrustKit'
  # Pods for Infrastructure

  target 'InfrastructureTests' do
    # Pods for testing
  end

end
